spring.data.mongodb.uri=mongodb+srv://kavishri:Kavi%402110@cluster0.lnazirq.mongodb.net/kanban_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=kanban_db

server.port=8080

# Disable auto-config of host/port so only URI is used
spring.data.mongodb.host=
spring.data.mongodb.port=